.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. chymera_qt test_chymera_qt
clean: FORCE
	$(MAKE) -C .. chymera_qt_clean test_chymera_qt_clean
check: FORCE
	$(MAKE) -C .. test_chymera_qt_check
chymera-qt chymera-qt.exe: FORCE
	 $(MAKE) -C .. chymera_qt
apk: FORCE
	$(MAKE) -C .. chymera_qt_apk
